App\Domain\GhaImport\Commit:
    type: entity
    table: commit
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        message:
            type: text
            options:
                collation: utf8mb4_unicode_ci
        commitId:
            type: string
    manyToOne:
        pushEvent:
            targetEntity: App\Domain\GhaImport\PushEvent
            mappedBy: commit
            orderBy: { createdAt: ASC }
