App\Domain\GhaImport\Comment:
    type: entity
    table: comment
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        repoName:
            type: string
        message:
            type: text
            options:
                collation: utf8mb4_unicode_ci
        commitId:
            type: string
